# Generated by Django 5.1.6 on 2025-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, default='driver_images/default.jpg', null=True, upload_to='driver_images/'),
        ),
    ]
