# Generated by Django 5.1.6 on 2025-03-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
