# Generated by Django 5.1.6 on 2025-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_driver_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
