# Generated by Django 5.1.6 on 2025-03-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_userprofile_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_hour',
        ),
    ]
