# Generated by Django 5.1.6 on 2025-03-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_remove_car_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('gcash', 'GCash')], default='onsite', max_length=10),
        ),
    ]
