# Generated by Django 5.1.6 on 2025-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_reservation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_approved_notif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled_notif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reason_for_cancelling',
            field=models.TextField(blank=True, null=True),
        ),
    ]
