# Generated by Django 5.1.6 on 2025-03-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_reservation_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid Yet'), ('paid', 'Paid')], default='not_paid', max_length=10),
        ),
    ]
