# Generated by Django 5.1.6 on 2025-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_reservation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='user', max_length=10),
        ),
    ]
