# Generated by Django 5.1.6 on 2025-06-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
