# Generated by Django 5.1.6 on 2025-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_reservation_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid Yet'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='not_paid', max_length=20),
        ),
    ]
