# Generated by Django 5.1.6 on 2025-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_alter_reservation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
