# Generated by Django 5.1.6 on 2025-08-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_car_seating_capacity_alter_car_image_carimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_confirmation_token',
            new_name='email_verification_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_email_confirmed',
            new_name='is_email_verified',
        ),
    ]
